### ISSUE TITLE
About VidVRD dataset

### ISSUE THREAD

**Issue by ZiyueWu59** [Dawn-LX/VidSGG-BIG#1]
Hello, could you provide your extracted tracklet data  `VidVRD_test_every1frames`? Thank you very much.

**Comment by Dawn-LX** [comment]
> Hello, could you provide your extracted tracklet data `VidVRD_test_every1frames`? Thank you very much.

here https://pan.zju.edu.cn/share/694f908a22fff11c037eb50876
and the link has been included in README.md

**Comment by ZiyueWu59** [comment]
> > Hello, could you provide your extracted tracklet data `VidVRD_test_every1frames`? Thank you very much.
> 
> here https://pan.zju.edu.cn/share/694f908a22fff11c037eb50876 and the link has been included in README.md

Thank you very much. Do you plan to release train set of vidVRD?

**Comment by Dawn-LX** [comment]
> > > Hello, could you provide your extracted tracklet data `VidVRD_test_every1frames`? Thank you very much.
> > 
> > 
> > here https://pan.zju.edu.cn/share/694f908a22fff11c037eb50876 and the link has been included in README.md
> 
> Thank you very much. Do you plan to release train set of vidVRD?

yes, the link has been updated in README.md just now
