### ISSUE TITLE
About the prepared data

### ISSUE THREAD

**Issue by Passenger33** [Dawn-LX/VidSGG-BIG#12]
Hello, when I download the prepared data, I find the VidVRD test data from zju needs the permission, and the pku data is no longer available. Could you please update the link? Thanks a lot.

**Comment by Awenjie10** [comment]
The same issue. Do you have solved this problem? Thanks.

**Comment by Dawn-LX** [comment]
> when I download the prepared data, I find the VidVRD test dat

The previous link expired, I updated one

try this：
Share a file (folder) for you: [VidVRD-test], click the link to view https://pan.zju.edu.cn/share/1d42cbbf6f13ab5520731e4310

**Comment by Passenger33** [comment]
> try this： Share a file (folder) for you: [VidVRD-test], click the link to view https://pan.zju.edu.cn/share/1d42cbbf6f13ab5520731e4310

It seems the zju's network disk is not so stable, whenever I try to download it, it will always show preparing to download. I think it may be the network disk's problem, could you please update a new link by another way? Thanks.

**Comment by Dawn-LX** [comment]
> 

ok.

**Comment by Dawn-LX** [comment]
> > try this： Share a file (folder) for you: [VidVRD-test], click the link to view https://pan.zju.edu.cn/share/1d42cbbf6f13ab5520731e4310
> 
> It seems the zju's network disk is not so stable, whenever I try to download it, it will always show preparing to download. I think it may be the network disk's problem, could you please update a new link by another way? Thanks.

ok

**Comment by Dawn-LX** [comment]
> > try this： Share a file (folder) for you: [VidVRD-test], click the link to view https://pan.zju.edu.cn/share/1d42cbbf6f13ab5520731e4310
> 
> It seems the zju's network disk is not so stable, whenever I try to download it, it will always show preparing to download. I think it may be the network disk's problem, could you please update a new link by another way? Thanks.

[here](https://mega.nz/file/wJhiwbbB#AR-YuKrS_uNEfypk9T1g-mb4GZFe7wEwIrmd7xtnRos) is the new link for `VidVRD_test_every1frames.zip`

**Comment by Dawn-LX** [comment]
I have also updated the link in README.md

**Comment by Passenger33** [comment]
> 

Got it, thanks a lot!

**Comment by ComeOnComeOnTurnYourRadioOn** [comment]
Hello,
Sorry for bothering you again.
I had already gone through the whole readme file but I still failed to find out the available link for downloading the tracklet data & features of the pku data (the link you post on the readme file isn't available anymore). So, for my current process, do I have to download the tracklet data & features in order to reimplement your work? If it is the case, could you please provide the new link for downloading these tracklet data & features of the pku data?

Thank you so much for your help. Looking forward to your response soon.
Cheers!

**Comment by Dawn-LX** [comment]
> Hello, Sorry for bothering you again. I had already gone through the whole readme file but I still failed to find out the available link for downloading the tracklet data & features of the pku data (the link you post on the readme file isn't available anymore). So, for my current process, do I have to download the tracklet data & features in order to reimplement your work? If it is the case, could you please provide the new link for downloading these tracklet data & features of the pku data?
> 
> Thank you so much for your help. Looking forward to your response soon. Cheers!

hello， the link of pku data  provided by pku's author  isn't available anymore. I will upload the data of their tracklet & feature on my own MEGA cloud. please wait one or two days. I have to download the data from the linux server first.

By the way, you can reimplement our work based on our tracklet data  first.

**Comment by ComeOnComeOnTurnYourRadioOn** [comment]
> > Hello, Sorry for bothering you again. I had already gone through the whole readme file but I still failed to find out the available link for downloading the tracklet data & features of the pku data (the link you post on the readme file isn't available anymore). So, for my current process, do I have to download the tracklet data & features in order to reimplement your work? If it is the case, could you please provide the new link for downloading these tracklet data & features of the pku data?
> > Thank you so much for your help. Looking forward to your response soon. Cheers!
> 
> hello， the link of pku data provided by pku's author isn't available anymore. I will upload the data of their tracklet & feature on my own MEGA cloud. please wait one or two days. I have to download the data from the linux server first.
> 
> By the way, you can reimplement our work based on our tracklet data first.

Okay! Thank you so much for your help!!

**Comment by Dawn-LX** [comment]
> > > Hello, Sorry for bothering you again. I had already gone through the whole readme file but I still failed to find out the available link for downloading the tracklet data & features of the pku data (the link you post on the readme file isn't available anymore). So, for my current process, do I have to download the tracklet data & features in order to reimplement your work? If it is the case, could you please provide the new link for downloading these tracklet data & features of the pku data?
> > > Thank you so much for your help. Looking forward to your response soon. Cheers!
> > 
> > 
> > hello， the link of pku data provided by pku's author isn't available anymore. I will upload the data of their tracklet & feature on my own MEGA cloud. please wait one or two days. I have to download the data from the linux server first.
> > By the way, you can reimplement our work based on our tracklet data first.
> 
> Okay! Thank you so much for your help!!

hello, the data of pku is here: https://mega.nz/file/UAgnXbjC#YqrlUe2rNl7qEEcr_NbxNk0qPX-Y5O2BZWVhHgqCK9g and I have also updated the README.md file

**Comment by ComeOnComeOnTurnYourRadioOn** [comment]
> > > > Hello, Sorry for bothering you again. I had already gone through the whole readme file but I still failed to find out the available link for downloading the tracklet data & features of the pku data (the link you post on the readme file isn't available anymore). So, for my current process, do I have to download the tracklet data & features in order to reimplement your work? If it is the case, could you please provide the new link for downloading these tracklet data & features of the pku data?
> > > > Thank you so much for your help. Looking forward to your response soon. Cheers!
> > > 
> > > 
> > > hello， the link of pku data provided by pku's author isn't available anymore. I will upload the data of their tracklet & feature on my own MEGA cloud. please wait one or two days. I have to download the data from the linux server first.
> > > By the way, you can reimplement our work based on our tracklet data first.
> > 
> > 
> > Okay! Thank you so much for your help!!
> 
> hello, the data of pku is here: https://mega.nz/file/UAgnXbjC#YqrlUe2rNl7qEEcr_NbxNk0qPX-Y5O2BZWVhHgqCK9g and I have also updated the README.md file

Wow!! Awesome!! Heaps of appreciation for your help! ;-)
