### ISSUE TITLE
The generation of .npy in prepared_data folder

### ISSUE THREAD

**Issue by Awenjie10** [Dawn-LX/VidSGG-BIG#13]
Hi, how did these .npy generate in prepared_data folder? pred_bias_matrix_vidvrd.npy and vidvrd_EntiNameEmb.npy. I did not find the corresponding code for these. Thank you.

**Comment by Dawn-LX** [comment]
> Hi, how did these .npy generate in prepared_data folder? pred_bias_matrix_vidvrd.npy and vidvrd_EntiNameEmb.npy. I did not find the corresponding code for these. Thank you.

can you download these  prepared .npy from MEGA cloud ?, [here](https://mega.nz/folder/tY5HQQwK#9Mgw4usgxF5FEI4RZArfmw))

**Comment by Dawn-LX** [comment]
In addition, you can generate the .npy for category name embds by `tools_draft/construct_CatName2vec.py`

**Comment by Awj2021** [comment]
> here

Yeah, I could download these .npy files

**Comment by Awj2021** [comment]
> In addition, you can generate the .npy for category name embds by `tools_draft/construct_CatName2vec.py`

file: tools_draft/construct_CatName2vec.py is used for generating the vidvrd_PredNameEmb.npy and vidvrd_EntiNameEmb.npy, but how about the pred_bias_matrix_vidvrd.npy? Thank you a lot.

**Comment by Dawn-LX** [comment]
> > In addition, you can generate the .npy for category name embds by `tools_draft/construct_CatName2vec.py`
> 
> file: tools_draft/construct_CatName2vec.py is used for generating the vidvrd_PredNameEmb.npy and vidvrd_EntiNameEmb.npy, but how about the pred_bias_matrix_vidvrd.npy? Thank you a lot.

Hi, sorry, I forgot to adding these files when updating tools_draft
Now I have updated the .py files for constructing bias.

refer to `tools_draft/construct_BiasMatrix.py` and `tools_draft/stat_triplet_bias.py`

You might have to change the dir of annotation, and change the CatId2Name map (currenlty is for PKU_vidvrd_CatId2name)

**Comment by Awj2021** [comment]
> 

Thank you very much.

**Comment by AmnaSaghi** [comment]
> > here
> 
> Yeah, I could download these .npy files

Could you please tell how you did it?

**Comment by Dawn-LX** [comment]
> > > here
> > 
> > 
> > Yeah, I could download these .npy files
> 
> Could you please tell how you did it?

What do you mean by "how I did it " ? 

Which part of the code that you not understand?

**Comment by Awj2021** [comment]
> > > here
> > 
> > 
> > Yeah, I could download these .npy files
> 
> Could you please tell how you did it?

I directly download these .npy files from the author's provided link.
