### ISSUE TITLE
Tracklet Data of VidVRD

### ISSUE THREAD

**Issue by ComeOnComeOnTurnYourRadioOn** [Dawn-LX/VidSGG-BIG#15]
Hello,
The link for downloading the tracklet data VidVRD_test_every1frames is invalid. Could you please provide the new one? 
Thank you very much.

**Comment by Dawn-LX** [comment]
> Hello, The link for downloading the tracklet data VidVRD_test_every1frames is invalid. Could you please provide the new one? Thank you very much.

hello., have you ever tried the link of MEGA cloud https://mega.nz/file/wJhiwbbB#AR-YuKrS_uNEfypk9T1g-mb4GZFe7wEwIrmd7xtnRos ? NOT the link of ZJU cloud

**Comment by ComeOnComeOnTurnYourRadioOn** [comment]
> > Hello, The link for downloading the tracklet data VidVRD_test_every1frames is invalid. Could you please provide the new one? Thank you very much.
> 
> hello., have you ever tried the link of MEGA cloud https://mega.nz/file/wJhiwbbB#AR-YuKrS_uNEfypk9T1g-mb4GZFe7wEwIrmd7xtnRos ? NOT the link of ZJU cloud

Ohh, thank you so much for your sharing. Since I was so struggling with finding out a workable link for downloading the tracklet data, I didn't fully go through all the readme files. 

Anyway! Thank you so much for your help and quick response! Cheers!
