### ISSUE TITLE
请问，可以提供一下用于提取I3D特征的I3D模型吗

### ISSUE THREAD

**Issue by whyang78** [Dawn-LX/VidSGG-BIG#19]
![image](https://user-images.githubusercontent.com/54824721/229054453-674fa7b5-4afa-48c3-95ad-27b9f37b1b99.png)  
请问可以提供一下I3D模型的链接吗 我想自己用于提取特征 谢谢

**Comment by Dawn-LX** [comment]
please refer to this repo:

https://github.com/piergiaj/pytorch-i3d

and the pre-trained I3D weights is here:
https://github.com/piergiaj/pytorch-i3d/tree/master/models

**Comment by whyang78** [comment]
谢谢



---- 回复的原邮件 ----
| 发件人 | Kaifeng ***@***.***> |
| 日期 | 2023年04月02日 15:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Dawn-LX/VidSGG-BIG] 请问，可以提供一下用于提取I3D特征的I3D模型吗 (Issue #19) |

please refer to this repo:

https://github.com/piergiaj/pytorch-i3d
