### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by MinamiKotoka** [Dawn-LX/VidSGG-BIG#2]
Hello, where can I get the file `prepared_data/vidvrd_EntiNameEmb_pku.npy` and `prepared_data/pred_bias_matrix_vidvrd_pku.npy`? I find no way to generate them by myself. Than you very much!

**Comment by Dawn-LX** [comment]
> Hello, where can I get the file `prepared_data/vidvrd_EntiNameEmb_pku.npy` and `prepared_data/pred_bias_matrix_vidvrd_pku.npy`? I find no way to generate them by myself. Than you very much!

sorry.

I have updated the link in README.md just now, https://mega.nz/folder/tY5HQQwK#9Mgw4usgxF5FEI4RZArfmw
and you can also find it in the README.md

**Comment by ZiyueWu59** [comment]
> > Hello, where can I get the file `prepared_data/vidvrd_EntiNameEmb_pku.npy` and `prepared_data/pred_bias_matrix_vidvrd_pku.npy`? I find no way to generate them by myself. Than you very much!
> 
> sorry.
> 
> I have updated the link in README.md just now, https://mega.nz/folder/tY5HQQwK#9Mgw4usgxF5FEI4RZArfmw and you can also find it in the README.md

Thank you for your update!
And there is another errer:
[Errno 2] No such file or directory: 
'preprocess_data/tracking/videovrd_detect_tracking/ILSVRC2015_train_00884000_myFaster18.npy'

This file does not exist. Could you update it? Thank you very much!

**Comment by Dawn-LX** [comment]
> 
> Thank you for your update! And there is another errer: [Errno 2] No such file or directory: 'preprocess_data/tracking/videovrd_detect_tracking/ILSVRC2015_train_00884000_myFaster18.npy'
> 
> This file does not exist. Could you update it? Thank you very much!

Thank you for reminding me this.

This file is supplement for the tracklet data released by paper "Beyond Short-Term Snippet: Video Relation Detection with Spatio-Temporal Global Context"

Because the original data released only have 999 `.npy` files, missing data for video `ILSVRC2015_train_00884000`

We trained our own Faster-RCNN (same training setting as the above paper), and extract the tracklet & features.

I have released these files [here](https://mega.nz/folder/FMhzFD4A#7R2c98TxgA7Av_b9-_ijYg)
And  I also have updated the README.md just now.

**Comment by guanw-pku** [comment]
Hi! Thanks for sharing this nice work.

There is another issue of missing data. The number of 
`.npy` files in VidVRD_train_every1frames is **792** [(link)](https://mega.nz/folder/1QA31RaK#pEP60O-ENr-5k_9ByoJhag). Does it should be 800?

Due to this, I got a error about `ILSVRC2015_train_00010008.npy`. Could you please upload the other files. 

Thank you soooo much!

**Comment by Dawn-LX** [comment]
> Hi! Thanks for sharing this nice work.
> 
> There is another issue of missing data. The number of `.npy` files in VidVRD_train_every1frames is **792** [(link)](https://mega.nz/folder/1QA31RaK#pEP60O-ENr-5k_9ByoJhag). Does it should be 800?
> 
> Due to this, I got a error about `ILSVRC2015_train_00010008.npy`. Could you please upload the other files.
> 
> Thank you soooo much!


Thank you for pointing out this !
Could you please tell me which 8 `.npy` files are missing?
Because when I upload them some error occurs and I can not identify which 8 `.npy` files are missing

**Comment by Dawn-LX** [comment]
> Hi! Thanks for sharing this nice work.
> 
> There is another issue of missing data. The number of `.npy` files in VidVRD_train_every1frames is **792** [(link)](https://mega.nz/folder/1QA31RaK#pEP60O-ENr-5k_9ByoJhag). Does it should be 800?
> 
> Due to this, I got a error about `ILSVRC2015_train_00010008.npy`. Could you please upload the other files.
> 
> Thank you soooo much!


For the following error:
```
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

use `np.load(path,allow_pickle=True)`

**Comment by guanw-pku** [comment]
The missing 8 files are

- `ILSVRC2015_train_00057001.npy`
- `ILSVRC2015_train_00061002.npy`
- `ILSVRC2015_train_00071013.npy`
- `ILSVRC2015_train_00040029.npy`
- `ILSVRC2015_train_00056001.npy`
- `ILSVRC2015_train_00010008.npy`
- `ILSVRC2015_train_00069005.npy`
- `ILSVRC2015_train_00040001.npy`

Thanks!

**Comment by Dawn-LX** [comment]
> The missing 8 files are
> 
> * `ILSVRC2015_train_00057001.npy`
> * `ILSVRC2015_train_00061002.npy`
> * `ILSVRC2015_train_00071013.npy`
> * `ILSVRC2015_train_00040029.npy`
> * `ILSVRC2015_train_00056001.npy`
> * `ILSVRC2015_train_00010008.npy`
> * `ILSVRC2015_train_00069005.npy`
> * `ILSVRC2015_train_00040001.npy`
> 
> Thanks!

I have uploaded them just now.

Now this [link](https://mega.nz/folder/1QA31RaK#pEP60O-ENr-5k_9ByoJhag) has 800 files

**Comment by guanw-pku** [comment]
Could you please update this file `ILSVRC2015_train_00040025.npy` in `VidVRD_train_every1frames` ? It seems corrupted because it can not be loaded.

**Comment by Dawn-LX** [comment]
> Could you please update this file `ILSVRC2015_train_00040025.npy` in `VidVRD_train_every1frames` ? It seems corrupted because it can not be loaded.

Done just now

**Comment by guanw-pku** [comment]
Sorry. Could you please update `ILSVRC2015_train_00815001.npy` ?

**Comment by Dawn-LX** [comment]
> Sorry. Could you please update `ILSVRC2015_train_00815001.npy` ?

Done.

**Comment by guanw-pku** [comment]
I re-downloaded this file `ILSVRC2015_train_00815001.npy` in this [Iink](https://mega.nz/folder/1QA31RaK#pEP60O-ENr-5k_9ByoJhag). But I still can not load this file using `np.load('.../VidVRD_train_every1frames/ILSVRC2015_train_00815001.npy', allow_pickle=True)`,  while other files I tries are normal. 

The 'Date added' seems still 2022-4-29. Dose it have not be updated successfully?

**Comment by Dawn-LX** [comment]
> 



> I re-downloaded this file `ILSVRC2015_train_00815001.npy` in this [Iink](https://mega.nz/folder/1QA31RaK#pEP60O-ENr-5k_9ByoJhag). But I still can not load this file using `np.load('.../VidVRD_train_every1frames/ILSVRC2015_train_00815001.npy', allow_pickle=True)`, while other files I tries are normal.
> 
> The 'Date added' seems still 2022-4-29. Dose it have not be updated successfully?

I deleted it and uploaded it again,. 

please try again.

**Comment by guanw-pku** [comment]
Thank you so much!

But it doesn't work. This file still can not be loaded using `np.load()`. So I can not use the dataloader_demo.py scipt to generate MEGA VidVRD train cache data.

Could you please check this `.npy` file using `np.load()` or upload the MEGA VidVRD train cache data ?

**Comment by Dawn-LX** [comment]
> Thank you so much!
> 
> But it doesn't work. This file still can not be loaded using `np.load()`. So I can not use the dataloader_demo.py scipt to generate MEGA VidVRD train cache data.
> 
> Could you please check this `.npy` file using `np.load()` or upload the MEGA VidVRD train cache data ?

I find this error
```
File "D:\Python_3_7\lib\site-packages\numpy\lib\npyio.py", line 441, in load
    pickle_kwargs=pickle_kwargs)
  File "D:\Python_3_7\lib\site-packages\numpy\lib\format.py", line 748, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated
```


it turns out that this file corrupted when I download it from my server. 

The corrupted file is 14.9 MB, while the complete file is 77.9 MB

I re-download it from my server, and re-uploaded it to MEGA cloud. please try again.

**Comment by guanw-pku** [comment]
Thank you!

Could you please release `classeme` data or the method of generating these files ?

**Comment by Dawn-LX** [comment]
> Thank you!
> 
> Could you please release `classeme` data or the method of generating these files ?

we only use classeme feature in VidOR, and we release the pre-prepared cache data, whcih includes classeme features

refer to here: https://github.com/Dawn-LX/VidSGG-BIG#tracklet-data-for-vidor


For VidOR, we use the weighted average of category word embeddings, based on the classification probability vectors predicted by the detector. ("soft" classeme) For VidVRD, we just use the category word embeddings as classeme feature, i.e., "hard" classeme.

**Comment by Dawn-LX** [comment]
> Thank you!
> 
> Could you please release `classeme` data or the method of generating these files ?

I have released some draft code, (refer to `tools_draft/extract_classeme.py`) see if they can help you

**Comment by guanw-pku** [comment]
> > Thank you!
> > Could you please release `classeme` data or the method of generating these files ?
> 
> I have released some draft code, (refer to `tools_draft/extract_classeme.py`) see if they can help you

Thanks for these scripts.

I changed the load_dir to the parent directory of these VidORtrain_freq1_m60s0.3_partxx files to run extract_logits.py, while I got the assertion error.

The length of res_path_list is 7006 not 7000. Besides, the assertion of box_info length return error as well. The length of the first box_info is 12 and the dimension of features is 1024.

There is the same issue (assertion error) in the extract_logits_val.py. The length of res_path_list is 842 not 835.

I also found that the load_dir in the original extract_logits_val.py is .../nms0.5_miss30_score0.3/..., while mine directory name is m60s0.3 (miss60_score0.3).

Could you please help me with these issues or release the generated classeme files?

Thank you!

**Comment by Dawn-LX** [comment]
> Thanks for these scripts.
> 
> I changed the load_dir to the parent directory of these VidORtrain_freq1_m60s0.3_partxx files to run extract_logits.py, while I got the assertion error.
> 
> The length of res_path_list is 7006 not 7000. Besides, the assertion of box_info length return error as well. The length of the first box_info is 12 and the dimension of features is 1024.
> 
> There is the same issue (assertion error) in the extract_logits_val.py. The length of res_path_list is 842 not 835.
> 
> I also found that the load_dir in the original extract_logits_val.py is .../nms0.5_miss30_score0.3/..., while mine directory name is m60s0.3 (miss60_score0.3).
> 
> Could you please help me with these issues or release the generated classeme files?
> 
> Thank you!

The classeme files is too large (i save them for every frame every box).

and, the 1024-dim feature is the RoI-pooled feature from MEGA, I did not release it, it's to large

`nms0.5_miss30_score0.3` is an ablation study, it not works well and not included in the paper. it has been deprecated

**Comment by Dawn-LX** [comment]
> Thanks for these scripts.
> 
> I changed the load_dir to the parent directory of these VidORtrain_freq1_m60s0.3_partxx files to run extract_logits.py, while I got the assertion error.
> 
> The length of res_path_list is 7006 not 7000. Besides, the assertion of box_info length return error as well. The length of the first box_info is 12 and the dimension of features is 1024.
> 
> There is the same issue (assertion error) in the extract_logits_val.py. The length of res_path_list is 842 not 835.
> 
> I also found that the load_dir in the original extract_logits_val.py is .../nms0.5_miss30_score0.3/..., while mine directory name is m60s0.3 (miss60_score0.3).
> 
> Could you please help me with these issues or release the generated classeme files?
> 
> Thank you!

In fact, you can use the "hard" classeme feature, as i mentioned above.
empirically the performance is similar.

Again, you can directly download the pre-prepared cached data, [here](https://github.com/Dawn-LX/VidSGG-BIG#tracklet-data-for-vidor)

**Comment by Dawn-LX** [comment]
move to issue3  https://github.com/Dawn-LX/VidSGG-BIG/issues/3  for further discussion
