### ISSUE TITLE
Make the qualitative results

### ISSUE THREAD

**Issue by tuanmanh1410** [Dawn-LX/VidSGG-BIG#20]
Thank you for your sharing the source code!
I would like to know how we can run experiments from Figure 6 in the paper.
And about the VidVRD Dataset, can we get qualitative results as visualization results?

**Comment by Dawn-LX** [comment]
we follow the visualization code from this : https://github.com/xdshang/VidVRD-helper/blob/master/visualize.py

**Comment by tuanmanh1410** [comment]
Thank you @Dawn-LX , I have tested with this above-mentioned visualize file.
But it seems to use the original video with ground truth annotation files to visualize the whole ground truth video. 

Following my understanding, to get results like Figure 6 in the paper for VidOR dataset, we need to use some information like triplets, duration, scores, sub_traj, and obj_traj inside "predic_relations" JSON file , is it right? Plz correct me if I am wrong.

**Comment by Dawn-LX** [comment]
> 



> Thank you @Dawn-LX , I have tested with this above-mentioned visualize file. But it seems to use the original video with ground truth annotation files to visualize the whole ground truth video.
> 
> Following my understanding, to get results like Figure 6 in the paper for VidOR dataset, we need to use some information like triplets, duration, scores, sub_traj, and obj_traj inside "predic_relations" JSON file , is it right? Plz correct me if I am wrong.

yeah, that's right. But I'm afraid that you have to write the visualization code based on [xdshang's code](https://github.com/xdshang/VidVRD-helper/blob/master/visualize.py) by yourself. The original visualization code of our paper is written separately with the project code,  based on the prediction results, e.g., here: https://github.com/Dawn-LX/VidSGG-BIG/blob/34a1a1eafec9e32cbd1fa8ce52fa73e9af0deee9/tools/eval_vidor.py#L257

**Comment by tuanmanh1410** [comment]
Thank you for your support. 
I will close this issue. Many thanks!!
