### ISSUE TITLE
轨迹提取的模型和细节

### ISSUE THREAD

**Issue by wangyongqi558** [Dawn-LX/VidSGG-BIG#22]
您好，我想做一些轨迹方面的消融实验，能提供一下您当时使用deepSORT方法时所用到的参数吗，另外还有提取物体的deepSORT feature时所用到的模型链接

**Comment by Dawn-LX** [comment]
> 您好，我想做一些轨迹方面的消融实验，能提供一下您当时使用deepSORT方法时所用到的参数吗，另外还有提取物体的deepSORT feature时所用到的模型链接



> 您好，我想做一些轨迹方面的消融实验，能提供一下您当时使用deepSORT方法时所用到的参数吗，另外还有提取物体的deepSORT feature时所用到的模型链接

你好，
参考这个repo，这一节： https://github.com/Dawn-LX/VidVRD-tracklets/blob/master/README.md#generate-object-tracklets-by-yourself
我们用的model 是MEGA

关于deepSORT的参数，参考这一节：： https://github.com/Dawn-LX/VidVRD-tracklets/tree/f0a64b40349f6f99052be6471a80868c6406eb99/deepSORT/tracking_results

**Comment by wangyongqi558** [comment]
谢谢
