### ISSUE TITLE
Device information

### ISSUE THREAD

**Issue by guanw-pku** [Dawn-LX/VidSGG-BIG#4]
When I loaded all the cached VidOR data and dataloader started  to fork, the program crashed due to error `OSError: [Errno 12] Cannot allocate memory`. I tried lower number of threads, but it did not work.

I am wondering whether my memory is too low (189GB, occupied memory is about 150+GB before crashing). Could you please provide your device information?

Thank you!

**Comment by Dawn-LX** [comment]
14parts training data need around 160G

**Comment by Dawn-LX** [comment]
you can use 1 parts for a demo

**Comment by guanw-pku** [comment]
Thanks for your information!
