### ISSUE TITLE
Classification stage and grounding stage

### ISSUE THREAD

**Issue by guanw-pku** [Dawn-LX/VidSGG-BIG#5]
Hi, I have a one question.

Could you please explain the choice that only applying classification stage on VidVRD dataset?

Thank you!

**Comment by Dawn-LX** [comment]
> Hi, I have a one question.
> 
> Could you please explain the choice that only applying classification stage on VidVRD dataset?
> 
> Thank you!

refer to Section 4.2 of our paper


. For each relation triplet in the training set of VidVRD [35], we noticed that only a portion of ground-truth segments is annotated as foreground, which makes the annotated temporal boundaries unreliable for training. Therefore, we only used the classification stage for VidVRD

**Comment by guanw-pku** [comment]
Thank you!
