### ISSUE TITLE
Negative coordinates in the proposal bounding boxes list

### ISSUE THREAD

**Issue by guanw-pku** [Dawn-LX/VidSGG-BIG#6]
Hi! 

I found some negative values in the bounding boxes of proposal. Does it have some special meanings?

Thank you!

**Comment by Dawn-LX** [comment]
> Hi!
> 
> I found some negative values in the bounding boxes of proposal. Does it have some special meanings?
> 
> Thank you!

first, refer to `tracking_results/format_demo.py`

second refer to  `_get_proposal` at   https://github.com/Dawn-LX/VidSGG-BIG/blob/3dde8e6d1f39b85ad384bd81b7b74fb17d7ba3f6/dataloaders/dataloader_vidvrd.py#L485

Third, if you mean the proposal `.npy` file from PKU, -1 means proposals that confidence = 0
