### ISSUE TITLE
About classme feature

### ISSUE THREAD

**Issue by MinamiKotoka** [Dawn-LX/VidSGG-BIG#7]
According to `tools_draft/extract_classme.py`, I run the `tools_draft/construct_CatName2vec.py` first. But no file named `vidor_CatName2vec_dict.pkl` is generated. Could you help me?
Thank you!

**Comment by Dawn-LX** [comment]
> According to `tools_draft/extract_classme.py`, I run the `tools_draft/construct_CatName2vec.py` first. But no file named `vidor_CatName2vec_dict.pkl` is generated. Could you help me? Thank you!

This is a dict version of `vidor_EntiNameEmb.npy`, please refer to `tools/construct_CatName2vec.py`

**Comment by ZiyueWu59** [comment]
> 

Hello, I have the same problem. There are no related code about generating `vidor_CatName2vec_dict.pkl` in `tools_draft/construct_CatName2vec.py`. Should I generate it by myself? If the key is the category of each entity and the value is the word embedding vector, and I name the generated file as `vidor_CatName2vec_dict.pkl`?
Thank you.

**Comment by Dawn-LX** [comment]
> 

Yes!, `vidor_CatName2vec_dict.pkl` is just a dict version of `vidor_EntiNameEmb.npy`

**Comment by MinamiKotoka** [comment]
> > 
> 
> Yes!, `vidor_CatName2vec_dict.pkl` is just a dict version of `vidor_EntiNameEmb.npy`

Hi, I run `extract_logits.py` and want to obtain `VidORtrain_freq1_logits` to generate `classme` file of VidOR. But the errors are the same as issue #3 . So how can I get  `VidORtrain_freq1_logits` ?
You say 'hard' classme feature, but it is for VidVRD. So what is 'hard' classme feature for VidOR? And how can I obtain it?
Thank you very much!

**Comment by Dawn-LX** [comment]
> 'hard' classme feature for VidOR

the 'hard' classme feature for VidOR is also predicate category text embedding
