### ISSUE TITLE
DEBUG model

### ISSUE THREAD

**Issue by aries-young** [Dawn-LX/VidSGG-BIG#8]
I find this snippet in grd_model_v5.py, which is used for DEBUG model to predict time boundaries. But, in regression head, why the left (right) offset is mapping to [0, 1] by sigmoid ? And how do you transform time boundaries to video frame feature sequences ?
```
        temp = nn.Sequential(
            DepthWiseSeparableConv1d(self.dim_hidden,self.dim_hidden,3),
            nn.ReLU()
        )
        temp2 = [copy.deepcopy(temp) for _ in range(4)] \
            + [DepthWiseSeparableConv1d(self.dim_hidden,self.num_bins,3)]
        temp3 = [copy.deepcopy(temp) for _ in range(4)] \
            + [DepthWiseSeparableConv1d(self.dim_hidden,2*self.num_bins,3),nn.Sigmoid()]
        
        self.cls_head = nn.Sequential(*temp2)
        self.conf_head = copy.deepcopy(self.cls_head)
        self.regr_head = nn.Sequential(*temp3)
```

**Comment by Dawn-LX** [comment]
We normalized the time into (0,1) w.r.t video range

**Comment by aries-young** [comment]
> We normalized the time into (0,1) w.r.t video range

Thank you so much. But if a long video has a small regression segment, which means the normalized offsets are also small values, does this affect localization performance?

**Comment by Dawn-LX** [comment]
> > We normalized the time into (0,1) w.r.t video range
> 
> Thank you so much. But if a long video has a small regression segment, which means the normalized offsets are also small values, does this affect localization performance?

maybe. long video is very annoying
