### ISSUE TITLE
About inference results

### ISSUE THREAD

**Issue by ZiyueWu59** [Dawn-LX/VidSGG-BIG#9]
Hi, when I evaluate grounding stage on VidOR by running `eval_vidor.py`, I find inference result has been load before evaluation, e,i,, `VidORval_infer_results_topk3_epoch60_debug.pkl'`. Could you introduce the structure of the data of the file?
Thank you very much!

**Comment by Dawn-LX** [comment]
> Hi, when I evaluate grounding stage on VidOR by running `eval_vidor.py`, I find inference result has been load before evaluation, e,i,, `VidORval_infer_results_topk3_epoch60_debug.pkl'`. Could you introduce the structure of the data of the file? Thank you very much!

oh, you have to evaluate the classification stage first and then save the infer_results, then evaluate the classification stage

**Comment by Dawn-LX** [comment]
> Hi, when I evaluate grounding stage on VidOR by running `eval_vidor.py`, I find inference result has been load before evaluation, e,i,, `VidORval_infer_results_topk3_epoch60_debug.pkl'`. Could you introduce the structure of the data of the file? Thank you very much!

for the detailed structure of `VidORval_infer_results_xxxx.pkl`, you can refer to the `infer_result_for_save` in this func: https://github.com/Dawn-LX/VidSGG-BIG/blob/3dde8e6d1f39b85ad384bd81b7b74fb17d7ba3f6/tools/eval_vidor.py#L19
